name: crawling weather & send message

on:
  schedule:
    - cron: '0 22 * * 0-4'

jobs:
  send-weather-alert-to-slack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '>=1.20.0'
    - name: get weather data
      id: weather
      run: |
        make run
    - name: Send to slack
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload-file-path: "./weather.json"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
